### ISSUE TITLE
~로 처녀를 잃었다 어디서 고침?

### ISSUE THREAD

**Issue by ERA213** [DarrnB/eraBAK-#10]
후부키는 투기장에서의 공중의 면전에서의 강간으로 <처녀>를 잃었다

암걸려 죽을 것 같은데 이거 어디서 고침

**Comment by DarrnB** [comment]
SHOP_LIFE66_전술대항전\闘技場_陵辱.ERB

**Comment by DarrnB** [comment]
vs코드 사용하면 드래그한다음 Ctrl + F2 누르면 일괄 변경 가능함

**Comment by DarrnB** [comment]
아 알고 있으려나

**Comment by ERA213** [comment]
근데 이거 CALL FUCK 끝에 문장 어디서 수정함?

인자를 수정해도 마지막은 ~으로 <부위처녀>를 잃었다 라고 고정돼서 "폭한의 뒷골목에서의 윤간"으로 <처녀>를 잃었다. 라고 써야됨.

"폭한에게 뒷골목에서 윤간"당해 <처녀>를 잃었다.
이런 식으로 출력하고 싶은데

**Comment by DarrnB** [comment]
그 부분은 어쩔 수 없이 그대로 두는게 맞을 듯 그거 수정하면 윤간용 함수 따로 만드는거 아니면
"화간으로<처녀>를 잃었다" 이문장도 
"화간당해<처녀>를 잃었다" 이렇게 됨 화간을 당하는건 이상하잖아

**Comment by ERA213** [comment]
ㅇㅇ CALL FUCK2로 따로만들거임

**Comment by DarrnB** [comment]
SYSTEM/FORCE_FUCK.ERB 여기 관련 함수 다 모여있음

**Comment by DarrnB** [comment]
문자출력은 나도 좀 찾아 봐야 할 듯

**Comment by DarrnB** [comment]
찾았는데 이거 @FUCK 함수가 아니라 @VIRGIN_COMMON 처녀 상실 함수에 달려있었음 
PRINTFORM %조사처리(시츄문자열,"로")% 
PRINTFORMW <처녀>를 잃었다…
이렇게 출력되는듯

**Comment by ERA213** [comment]
ㅇㅋㅇㅋ 이건 좀 신중하게 건드려야 할듯

**Comment by DarrnB** [comment]
SIF로 한줄 추가해서 
SIF 시츄문자열 == "폭한에게 뒷골목에서 윤간"
PRINTFORM %시츄문자열% 당해 
PRINTFORMW <처녀>를 잃었다…
이렇게 하면 굴러가긴 할 듯?

**Comment by DarrnB** [comment]
근데 굳이 이렇게까지? 싶다

**Comment by DarrnB** [comment]
할꺼면 하고 조금 지저분 해 지는 거 말곤 문제는 없을 듯
