### ISSUE TITLE
사야 스킬 개사기 아님?

### ISSUE THREAD

**Issue by ERA213** [DarrnB/eraBAK-#15]
의도한건지 모르겠는데 다단히트가 10번인가 들어가면서 상대 병력 1/3을 날려버리던데

**Comment by DarrnB** [comment]
딜이라면 5랩 미카스킬이 근 5000딜을 박고 2랩 시로코스킬이 100%확률로 1200딜씩 박는데 
무투방위 개 딸리는 사야가 2000딜정도는 박아줘야 쓸 만 한게 아닐까?

**Comment by ERA213** [comment]
내가 잘못본게 아니라면 상대 병력이 12000에서 8000대까지 떨어졌음 스샷 찍어둘걸 그랬네

**Comment by ERA213** [comment]
병력 꼴랑 5~6천 들고 공방지 FF무인 병력으로 아무리 똑같이 공방지FF무인 상대라지만 다단히트 주르륵 찍히면서  스킬 페이즈부터 병력을 갈아버리길래 깜짝 놀람

**Comment by DarrnB** [comment]
4천 정도면 운 좋으면 뜰 수도 있는 딜이긴 한데 일단 계수 2.0에서 1.5로 낮춤
