### ISSUE TITLE
메인스토리 시작 시점

### ISSUE THREAD

**Issue by ERA213** [DarrnB/eraBAK-#19]
1. 총학생회장 실종 직후?
2. 원래라면 센세가 왔어야 할 시점?
3. 아니면 모든게 끝나고 센세의 사망 직후?

각각의 경우 메인 스토리를 이렇게 짤 수 있음

1. 총학생회장이 실종되고 몇 턴 동안은 인프라가 유지되며 평화가 유지되었지만, 점차 치안이 불안정해지고 불만이 폭주하며 대전쟁 발발 - 총학생회는 상황을 수습하려 했지만 폭주하는 게헨나에 의해 점령당하고 통제력을 상실 - 게헨나, 트리니티, 밀레니엄이 서로를 견제하는 삼파전 구도

2. 선생님이 와야 할시점에 선생님이 오지 않아 서서히 통제력을 잃은 총학생회와, 그런 총학생회를 SRT, 카이저와 손잡고 카야가 전복해 카야 통치기 시작. 린을 비롯한 기존 총학생회 멤버들은 방랑. 혹은 총학생회 잔당으로 남아 카야랑 싸우다 멸망하거나, 아유무(트리니티), 모모카(하이랜더), 아오이(밀레니엄), 하이네(게헨나) 식으로 망명. 린은 붙잡힌 상태. - 3세력 동맹에 힘입은 카야가 총학생회 권한으로 몇주간 트롤링하는 이벤트 - 카야의 철권통치에 불만을 품은 학원들이 물밑에서 작업. - 군웅할거

3. 색채 잔당, 여전히 도사리는 데카그라마톤의 위협. 센세의 죽음에 충격받은 학생들. 회개하고 풀려나 총학생회를 지지하는 카야. - 하지만 또다시 생텀 타워는 붕 뜬 상태가 되었고 인프라는 멈춰버림. 철도가 멈추자 하이랜더가 날뛰며 곳곳을 약탈하며 열차를 계속 굴린다는 설정. - 불안해하는 학원들을 총학생회가 최대한 결집하려 했지만, 게헨나와 트리니티의 갈등에 다시 불이 붙고 서로가 서로의 내부 반대파를 숙청하며 분열, 다시 전투가 벌어짐 - 혼란을 틈타 카이저가 아비도스를 침공하고, 색채 잔당이 서서히 모습을 드러내며 키보토스를 위협.

맘에 드는 걸로 골라보셈. 이 내용에 따라 스크립트 스토리나 말투, 분위기가 다 달라짐

**Comment by DarrnB** [comment]
이건 여기말고 챈에다 물어봐야 할 것 같긴 한데 난 개인적으로 설정이랑 이름만 똑같은 평행세계라고 생각하고 
아예 원작 스토리라인 무시하고 처음부터 새로 짜야한다고 보긴 함. 
애초에 선생이 학생이랑 야스하는 부분에서부터 개연성은 작살이라

**Comment by ERA213** [comment]
ㅇㅇ 챈에도 올림.
애초에 학생이 동물인 시민이 씨좀 뿌렸다고 임신하는게 말이 안되긴 함ㅋㅋㅋ
