### ISSUE TITLE
데일리 IS_FEMALE

### ISSUE THREAD

**Issue by ERA213** [DarrnB/eraBAK-#20]
이거 붙은거 보면 거의 대부분 플레이어가 여자인지 묻고 여자면 남자랑 ㅅㅅ로 이어지는데

이거 전부 IS_MALE로 바꿔보려함.

바꾸면서 어색한 스크립트는 수정을 하든 창작을 하든 해서 인간 남자가 없다는 설정을 구현해볼 생각인데 어떻게 생각함?

참고로 이게 세계관에 완벽하게 들어맞게 하려면 종족 탭 만들어서 [기계], [수인], [인간], [학생] 으로 구분하고 인간 - 남성 일 경우에만 작동하게 해야 함

**Comment by DarrnB** [comment]
정확히 이해가 안되는데 발생판정에
SIF !IS_FEMALE(MASTER)
	RETURN 0
이게 들어가서 플레이어가 여성일때만 발생하는 이벤트를 전부 수정하겠다는 뜻?
여성 플레이어로 하는 사람도 있을 수 있는데 이 부분은 어떻게 함

그리고 IS MALE로 바꾼다는건 또 무슨 소린지 모르겠음 
플레이어가 여성일때만 발생하는 이벤트를 플레이어가 남성일때만 발생하게 바꾼다는거임?

단순히 검색해봐도 IS_FEMALE 들어가는 줄이 298줄이 나오는데 이걸 스크립트까지 다 수정한다고?
좀 심하게 노가다 같은데 가능함?

플레이어 종족을 [기계], [수인], [인간], [학생] 으로 구분하고 플레이어가 인간 - 남성 일 경우에만 발생하는 이벤트로 만든다 
내가 이해한게맞음? 이해한게 맞다면 어차피 인간 남성으로만 이벤트가 나오는데 다른 종족이나 성별을 굳이 추가할 이유가 있음?

종족 부분은 의미가 없음 에초에 캐릭터는 학생밖에 나오질 않고 다른 종족 캐릭터를 추가 한다고 한 들 수가 턱없이 모자라서 굳이 귀찮게 종족까지 추가 할 필요가 없음

다만 태그는 지금은 학원 하나 있는데 이건 추가할 생각이 있음 [게헨나][선도부][부장] 이런식으로 태그 여러개인것도 나쁘진 않을거 같음

**Comment by DarrnB** [comment]
그리고 선생제외 인간남성이 하나도 없다는 설정은 난 솔직히 찬성이긴 해
근데 이것도 챈에 한번 물어봐야할듯 기존K 가 NTR범벅이였던거 생각하면 인간 남성 없다는 이유로 버려지는 껄리는 시츄가 있을 수도 있잖아

**Comment by ERA213** [comment]
이해한거 다 맞고 씹노가다임. ㅅㅅ이벤트가 죄다 부원이나 용병이 플레이어를 덮치는 이벤트인데 이게 죄다 여자일 때 남자인 상대에게 당하는거라 ㅈ같음. 블아K 솔직히 누가 여자로 함? 그래서 이걸 싹다 바꿀 생각.
종족은 굳이 추가 안해도 되긴 할듯 ㅇㅇ

**Comment by ERA213** [comment]
지금 데일리 하나 바꾸고 테스트해볼 생각인데 이벤트 어케 바로 보는지 방법 몰라서 챈에 검색하러 가는중임

**Comment by DarrnB** [comment]
플레이어 성별 남성 고정은 챈에 한번 물어보고 결정하는게 맞는거같고
만약 남성으로 고정할꺼면 굳이 
SIF !IS_MALE(MASTER)
	RETURN 0
이부분은 어차피 플레이어는 남자니까 그냥 싹 지워버려도 무방하긴 함

**Comment by DarrnB** [comment]
구상 데일리 말고 전역 데일리 같은 경우는 CREATE_DAILY_MAP.ERB 에 
CALL REGISTER_DAILY 로 데일리 불러 와 주고 데일리 내에 RATE 함수 리턴값 1000주면 턴넘길때 100% 실행됨

**Comment by DarrnB** [comment]
DECISION 함수도 싹 비워놓으면 조건에 상관없이 실행되고

**Comment by DarrnB** [comment]
기존 이벤트는 남겨 놓고 고대로 복사해서 남성용 이벤트로 새로 만드는 방식으로 합시다.
기존 이벤트 일단 남겨 놓는 게 여러모로 좋을 듯

**Comment by ERA213** [comment]
ㅇㅋㅇㅋ
