### ISSUE TITLE
농땡이마왕 뭘로 바꾸는게 좋을 것 같음?

### ISSUE THREAD

**Issue by ERA213** [DarrnB/eraBAK-#22]
스미레 트레이닝 수정중인데 K시리즈 몰루K로 처음 접하고 제일 당황했던게 이 [농땡이마왕]이란 거였음.

동방도 아니고 블아도 아니고 농땡이마왕은 어디서 튀어나온거지? 이 생각이 제일 먼저 듦. 나중엔 그냥 잊어버렸지만.

일단 확실한 건 이게 농땡이마왕이란 이름으로 남아있으면 안된다는 거임.

그래서 생각한 제일 유력한 이름은 히키코모리

아니면 비행청소년

근데 히키코모리는 란K때 농땡이랑 별개로 봤던 이름이라 헷갈릴 것 같음. 쓴다면 은둔형 외톨이가 좋을듯

비행청소년은 스스로 성장을 멈췄다는 점에서 근본적으로 농땡이랑 비슷한 부류라고 생각됨. 가장 적절한 명칭이 될 수 있음

뭐가 좋을 것 같음? 일단 내 선택은 글자수를 맞출 수 있다는 점에서 비행청소년임

**Comment by DarrnB** [comment]
지금 농땡이마왕 디폴트로 붙어있는 애들이 후부키,모모카,치아키,호시노,이로하 임 비행청소년 보단 '농땡이' 자체에 초점을 맞춘 개명이 좋을 듯 한데

**Comment by DarrnB** [comment]
굳이 바꾼다면 게으름뱅이 정도?

**Comment by ERA213** [comment]
게으름뱅이 나쁘지 않을듯
