### ISSUE TITLE
이벤트 다 끄니까 재미가 없음

### ISSUE THREAD

**Issue by ERA213** [DarrnB/eraBAK-#29]
키보토스 데일리가 많은 것도 아닌데 바로 다 꺼버리니까 하는 재미가 없음

말투는 번역체에 세계관도 다르고 고증도 다르더라도 일단 데일리는 전부 활성화 시키는게 좋을 것 같음

재미가 없으니 의욕이 안 남

처음 하는 사람들은 일단 다 [예] 누르고 볼텐데 그런 사람들이 볼 거라고는 농땡이마왕이랑 조깅, 스미레뿐임. 그렇게 떨어져나갈 건덕지 자체를 주지 말아야 함.

**Comment by DarrnB** [comment]
데일리 전부 활성화 시키는건 나도 동의하는데 방법이 몇가지 있음

1. 원작자가 한땀한땀 달아놓은 FLAG:데일리이벤트_미검수 플래그를 다 뗀다
2. FLAG:데일리이벤트_미검수를 디폴트로 1로 만든다

2번의 경우에는 원작자가 뉴게임 루프에 데일리 설정을 완성을 안 시켜놔서 완성시킬 필요가 있음 (끄는걸 원하는 사람이 있을수도 있으니까)
난 당연히 2번이 낫다고 보는데 데일리 설정 만드는거 어려운것도 아니고 근데 대체 왜 데일리 이벤트 태그를 FLAG로 저장한지는 모르겠네

**Comment by DarrnB** [comment]
근데 이후 추가 데일리 만들 거 생각하면 FLAG도 다 떼는게 맞긴 해

**Comment by DarrnB** [comment]
일단 데일리 설정 간단하게 만들어 봄

**Comment by DarrnB** [comment]
혹시 작업한 데일리들 미검수 태그 땠음?

**Comment by ERA213** [comment]
ㄴㄴ 아직 다 붙어있음

**Comment by DarrnB** [comment]
원작자가 미검수 붙여놓은게 환상향 데일리라 키보토스에 안 어울려서 붙여 놓은거 같으니까 수정한건 미검수 떼도 될 듯
일단 데일리 기본 설정은 전부 켜져있는걸로 하고 수동 설정으로 하나씩 온오프 할 수 있게 해놓을게

**Comment by ERA213** [comment]
일단 미검수만 다 떼주면 스크립트만 건드는 선에서 최대한 맞춰봄

**Comment by ERA213** [comment]
ㄱㄱ을 당하는 상황은 되도록 수인 시민들한테 당한다는 설정으로

**Comment by DarrnB** [comment]
내가 떼는거 보단 직접 스크립트 작업끝나면 떼는 식으로 하는게 낫지 않어?

**Comment by DarrnB** [comment]
떼는 거 보단 이벤트에 맞는 FLAG로 바꿔 다는게 나을듯

SIF FLAG:데일리이벤트_미검수 == 0
	RETURN 0

이부분을 

SIF FLAG:데일리이벤트_에로 == 0
	RETURN 0

이런식으로 

이렇게 해야 데일리 설정할 때 제대로 온오프 될 듯

**Comment by DarrnB** [comment]
그것도 아니면 그냥 스크립트 작업 완전히 끝난건 윗줄에 주석으로 표시 해 놓으면 내가 읽어보고 알아서 추가함

**Comment by ERA213** [comment]
ㅇㅋㅇㅋ

**Comment by DarrnB** [comment]
일단 미검수까지 전부 다 켜는걸로 설정 해놨고 데일리들 정상 작동하는거 확인했음
미검수 데일리들 어느정도 수정하고 나서 미검수는 꺼 놓는 걸 기본 설정으로 바꾸면 될 듯
