### ISSUE TITLE
이건 그냥 구상인데

### ISSUE THREAD

**Issue by ERA213** [DarrnB/eraBAK-#31]
와카모 던전 만들어서 란스K 시즈카 나기 이벤트처럼 구성하면 괜찮을 것 같음

데일리로 와카모가 일을 벌였다는 소식 전달 -> 던전, 혹은 산책에 와카모 포획 선택지 추가 -> 던전 탐색

사지절단 당해서 실험용 수조에 갇힌 할배 하나 놓고 나기가 시즈카 괴롭히는 이벤트처럼

와카모에게 도달하려면 정면돌파로 빠르게 가거나, 지체되더라도 옆으로 돌아가거나 둘 중 하나 골라 전진 -> 빠르게 온 만큼 와카모를 공격할 수 있는 턴수가 늘어남 -> 전투 중에 턴수가 0이 되면 와카모 도주. || 남은 턴수가 0이 되기 전에 와카모를 쓰러뜨리면 센세처럼 훈육하거나 자기 학원으로 납치하거나 선택.

훈육을 선택할 경우 와카모가 플레이어를 밤중에 몰래 찾아와 애정행각을 벌이는 연모 루트, 납치할 경우 평범한 조교 복종 루트. 대신 복종이나 예속 달릴 때마다 이벤트 넣어주면 좋을듯.

여태까진 작업 빡셀까봐 이런 구상들 말 안하고 있었는데 이번에 챈에 구상 물어보길래 써봄. 하나코하루 구상도 있는데 필요하면 말하셈

**Comment by DarrnB** [comment]
던전 시스템을 통째로 만들어야 하는거라 이벤트 하나 때문에 만들긴 빡쌔고 차라리 지금 만들고 있는 총력전에 와카모를 추가해서 

데일리 이벤트 발생 -> 총력전에 와카모 추가 -> 승리시 어쩌구저쩌구 

이렇게 하는게 현실적으로 가능할듯? 게다가 와카모 총력전이랑 데일리는 이미 생각중이였기도 하고

**Comment by DarrnB** [comment]
승리시에는 그냥 사관으로 추가하려고 했는데 너가 적어놓은 식으로 하는게 좋을듯

**Comment by ERA213** [comment]
아예 칠수인들 전부 총력전으로 영입하게 만드는것도 좋을 것 같음. 얘네가 어디 영입제안 받는다고 들어갈 애들이 아니니까

**Comment by DarrnB** [comment]
ㅇㅇ 맞긴해

**Comment by ERA213** [comment]
아키라는 예고장 이벤트, 카이는 노출된 연구실을 습격하는 식으로

**Comment by DarrnB** [comment]
이런 시스템추가가 필요한 이벤트는 현실적으로 시간이 좀 걸리고
그냥 평범한 데일리같은건 그냥 대충 싸질러주면 내가 함수나 변수같은건 뚝딱뚝딱 만들어 줄 수 있다

**Comment by ERA213** [comment]
ㅇㅋㅇㅋ 평범한 데일리도 생각해봄
