### ISSUE TITLE
데일리 요청, 건의사항

### ISSUE THREAD

**Issue by DarrnB** [DarrnB/eraBAK-#32]
코드 짜긴 귀찮고 데일리는 만들고 싶다 
텍스트만 써 주면 언젠간 만들어 줌

**Comment by LemonGreeentea** [comment]
옙 ^^7

**Comment by ERA213** [comment]
혼자 작업하다 오래걸릴것 같아서 일단 미리 올려봄

**Comment by ERA213** [comment]
[학원 방랑.txt](https://github.com/DarrnB/eraBAK-/files/15132597/default.txt)

**Comment by DarrnB** [comment]
쭉 읽어봤는데 
플레이어가 방랑일때만 발생
세력선택 -> 선택세력중 랜덤 학생을 만남

주석을 보니 이벤트 진행에 따라 요바이에도 추가 내용이 생기게 하고

몇 가지 얘기할 부분이 
일단 만나는 대상이 남자일 경우는 굳이 만들 이유가 있나? 남자 하나도 없잖아

이게 아무래도 모든 캐릭터가 다 등장 할 수 있는 데일리다 보니까 말투 관련해서 적어놓은 부분이 있던데
캐릭터마다 아예 특이한 말투인 애들도 많아서 이게 다 처리가 가능할 지가 문제네

가장 중요한게 플레이어 방랑시 발생하는 이벤트인데 몰루K에서 플레이어가 방랑인경우가

1. 방랑스타트
어차피 몇턴 안에 다른 세력 들어감
2. 다른 세력 들어가려고 세력 나옴
이것도 몇턴 안에 다른 세력 들어감

방랑 컨텐츠가 아예 전멸인데 차라리 방랑에 관계없이 진행되게 하는 게 낫지 않을까?

그래서 결국 내가 뭘 해줬으면 하는거임?
일단 여기까지 만들어 놨으니까 완성을 시켜달라는거?
기술적인 도움이 필요한거?

**Comment by DarrnB** [comment]
ㅇㅋ 일단 글에 써놓은거 구현할 함수들은 만들어서 주석 달아놓을게

'선택한 세력에서 학생 선택해 저장하는 코드' 
이거 말하는게 다음 이벤트에서도 사용하려고 저장해 놓는 게 맞음?

**Comment by ERA213** [comment]
ㄴㄴ 그건 그냥 이번 이벤트에서만 쓰는거. Local:0 같은데다 저장해서 이름 부를 때 쓰겠다는 말임.

그렇게 쓰는 것도 생각은 해봤는데 머리아파서 거기까지는 안 가기로 함.
전역변수 방랑학원플래그도 그냥 요바이 시작할 때 조건 확인하고 0으로 만든 다음 대사 몇줄 출력시키는게 그 전역변수 역할의 전부임

**Comment by DarrnB** [comment]
일단 선택 세력에서 랜덤 학생 뽑는 함수는 만들었는데 
써놓은 글 자세히 읽어보니까 솔직히 뭐가 뭔지 하나도 모르겠다 첫줄부터 고비임
IF 학원방랑거절플래그 == 0
ELSE
ENDIF
이걸 원하는거 같은데 밑에 보니까 

IF 학원방랑거절플래그 == 1 

이거 따로 있는거보고 정신 잃을 뻔 했다 에초에 학원방랑거절플래그가 무슨 역할을 하게 하려고 한지도 모르겠음

그냥 글로 풀어서 적어 줄 수 있음?
내가 알아서 깔끔하게 정리할게

**Comment by DarrnB** [comment]
적어놓은 부분까지 전부 만들어서 키보토스 기타에 넣어놨음 미검수 태그는 안달았고 발동확률만 0으로 해놓음
어느정도 작동 하는건 확인 했는데 아주 세세히 보진 않음

**Comment by DarrnB** [comment]
상단에 색 바꾸는 코드 몇개 넣어놓고 주석 달아놨으니까 확인하고 알아서 쓰시오

**Comment by ERA213** [comment]
ㄱㅅㄱㅅㄱㅅㄱㅅ

**Comment by DarrnB** [comment]
지금 테스트 중인데 문제가 많다

**Comment by DarrnB** [comment]
수정해서 다시 올림 변수 초기화를 안해서 생긴 버그였다

**Comment by ERA213** [comment]
ㅇㅋㅇㅋㄱㅅㄱㅅ

**Comment by DarrnB** [comment]
근데 이게 생각해보면 랜덤 세력을 고르는 부분은 없어지는게 나은거같다
이런식으로 뽑으면 사관이 적은 세력의 학생들이 상대적으로 많이 나오게 됨

**Comment by DarrnB** [comment]
에초에 랜덤 세력을 뽑는 부분이 무의미하잖아

**Comment by ERA213** [comment]
ㄴㄴ 그거 입부하러 왔다 선택지 때문에 그렇게 해야 했음. 그리고 모든 도시를 방랑한다는 컨셉인데 학생 적은 학원에서 같은 학생 자주 마주치는건 고증 아님?

**Comment by DarrnB** [comment]
입부하러 왔다 선택지는 랜덤세력 선택하는거랑 아무 상관이 없음 어차피 세력은 학생만 있으면 찾을 수 있으니까 따로 뽑을 필요는 없음
뭐 고증때문에 그렇게 한다면야 더 할말은 없다

**Comment by DarrnB** [comment]
플레이어의 행동이 "누굴 만난다" 가 아니라 "어딜 간다" 에서 어쩌다 보니 누군가를 만나는 거니까 흐름상 이상하진 않긴 해

**Comment by ERA213** [comment]
ㅇㅇ 다른데 학생 많다고 학생 적은 학원만 적게 가면 좀 불편할것 같음
