### ISSUE TITLE
데이트 개편안

### ISSUE THREAD

**Issue by LemonGreeentea** [DarrnB/eraBAK-#33]
1. [데이트]의 탭 위치를 특수 -> 친교로 이동
2. 데이트 장소를 호수, 산, 숲, 마을, 꽃밭, 자택에서 몰루에 나오는 주요 도시나 장소로 변경(소모되는 크레딧도 변경)
3. 2번과 연계하여 특정한 장소를 점령하거나 점령한 세력과 정전/동맹 상태에서 방문할 수 있는 장소 추가
4. 데이트 할 때 구상이 출력될 수 있도록 구상 템플릿 업데이트(데이트를 한 구상으로 다 퉁치거나 장소에 따라 구상이 달라질 수 있도록 설계)

이 정도로 만들까 생각중인데 다른 좋은 의견 있으면 말해줘

**Comment by DarrnB** [comment]
타국 방문하면 해당 나라 사관들 랜덤으로 만나는 것도 좋을 듯

**Comment by LemonGreeentea** [comment]
타국에서 만난 학생들 안면이나 호감도 소폭으로 올라가는것도 괜찮을듯

**Comment by DarrnB** [comment]
그리고 데이트 보상도 좀 생각해 볼 필요가 있을 듯 지금은 그냥 호감도 주고 땡인데 
오르는 호감도도 스탯 50기준 100~200 언저리고 
이게 그냥 만나러간다에서 포도주 두번 맥이고 대화 갈기는거나 큰 차이가 없음

**Comment by DarrnB** [comment]
데이트 시츄를 잔뜩 추가하면 구상 보려고라도 하겠지만 현실적으로 어려울것 같고
차라리 TIMES같은거 써서 비율로 올리는건 어떤가 싶다
연모에서 친애달기 쉽게 솔직히 1500 -> 10000은 좀 빡쌔니까

에초에 쌩판 남이랑 데이트 하는거랑 연모달린 사람이랑 데이트 하는게 호감도가 똑같이 오르면 이상하잖아

**Comment by LemonGreeentea** [comment]
확인. 일단 개편 먼저 하고 보상은 맨 나중에 바꿔보겠음
