### ISSUE TITLE
CALL FUCK에 쿤닐링구스 넣을 수 있음?

### ISSUE THREAD

**Issue by ERA213** [DarrnB/eraBAK-#34]
용병 상대로 펠라티오 했다고 써있는거 전부 쿤닐링구스로 바꾸고 싶은데 뭐라고 적어야 함?

**Comment by ERA213** [comment]
CALL FUCK(LOCAL:5, "욕망, 정애, 봉사, 성교, 성기술, 노출, 노출, 펠라티오, Ｖ감", "키스상실, 처녀상실, 질내사정, 구강사정", GET_SPERM_ID("병사"), "병사의 페니스", "병사", "", "외교적 요구에 대한 포상 조교")

를

CALL FUCK(LOCAL:5, "욕망, 봉사, 성기술, 노출, 노출, 쿤닐링구스, C감", "키스상실", GET_SPERM_ID("병사"), "", "", "", "외교적 요구에 대한 포상 조교")

대충 이정도로 바꾸고 싶음

**Comment by DarrnB** [comment]
두번째 인자 싹 살펴보니 쿤니는 없음 레즈 정도 추가하고 키스상실 대상을 대상의 질 이런식으로 하는게 최선일듯

**Comment by DarrnB** [comment]
CALL FUCK(LOCAL:5, "욕망, 봉사, 성기술, 노출, 노출, 레즈, C감", "키스상실", "대상의 질", "", "", "외교적 요구에 대한 포상 조교")

이정도면 될 듯? 레즈플이니 get_sperm_id 는 뺌

**Comment by DarrnB** [comment]
이제보니 노출이 두개 들어갔네

**Comment by DarrnB** [comment]
아예 exp.csv를 봐도 쿤니 관련 경험치는 없다

**Comment by ERA213** [comment]
레즈플인데 쿤닐이 없다니

**Comment by ERA213** [comment]
저기 근데 알파벳으로 C V A B M이랑 C감 V감 이거랑 차이가 뭐임? 하나만 써도 되는거임?

**Comment by DarrnB** [comment]
인자에 C감이라고 적힌게 있음? 그냥 C라고만 적어야 할텐데?

**Comment by DarrnB** [comment]
CALL FUCK(LOCAL:5, "Ｃ, Ｂ, Ｍ,욕망, 봉사, 성기술, 노출, 노출, 레즈", "키스상실", "병사의 질", "", "", "외교적 요구에 대한 포상 조교")
