### ISSUE TITLE
이거 어케고침

### ISSUE THREAD

**Issue by ERA213** [DarrnB/eraBAK-#43]
![if talent 에러](https://github.com/DarrnB/eraBAK-/assets/56868275/23b5171f-ddb1-4cbb-b771-b5fa92d2d47e)

https://github.com/ERA213/eraBAK-/blob/master/ERB/SYSTEM/EVENT_DAILY/%ED%82%A4%EB%B3%B4%ED%86%A0%EC%8A%A4_%EA%B8%B0%ED%83%80/WANDERING_%ED%95%99%EC%9B%90%EB%B0%A9%EB%9E%91.ERB

if문 talent:선택학생: 부분에서 오류가 나는 것 같은데 해결방법 있음?

**Comment by DarrnB** [comment]
어디 endif 빠진거같은데?

**Comment by ERA213** [comment]
빠진 게 아니라 하나가 더 들어가있었음ㅋㅋㅋㅋ
